### ISSUE TITLE
Repo size badge stays at 390mb+ even after removal of training images worth of 300mb+

### ISSUE THREAD

**Issue by raymelon** [pic2mood/Eliana#45]
See [README.md](https://github.com/raymelon/Eliana/blob/master/README.md)

**Comment by GeoZac** [comment]
Git keeps the files inside a hidden folder in case the user wants to revert to that at later point of time, so the files were only removed out of the current branch, while the still exists in folder.

**Comment by raymelon** [comment]
Will check on that.

At first I thought it is a [reposs](https://github.com/ruddfawcett/reposs) bug, but upon trying other services like [github-size-badge](https://github.com/axetroy/github-size-badge), the results are similar. Got 396.1mb and 408mb respectively.

Thanks @GeoZac
